### ISSUE TITLE
can't catkin_make this package

### ISSUE THREAD

**Issue by Yu1107** [r5cop/x80sv#1]
i want to use  x80sv 

but i'm face this problem:

![screenshot from 2018-11-17 15 36 39](https://user-images.githubusercontent.com/45117503/48658535-a03e0c80-ea7e-11e8-9fcc-a0e58accdd59.png)

**Comment by reinzor** [comment]
Hi, unfortunately this package is no longer publicly maintained.

**Comment by Yu1107** [comment]
Thanks
